from .config import (
    PROMTE_WHISPER_URL,
    PROMTE_4O_URL,
    PROMTE_API_KEY,
    MODEL_URL_MAP,
    AZURE_SPEECH_KEY,
    AZURE_OPENAI_KEY,
    STATUS_CREATED,
    STATUS_LANGUAGE_SET,
    STATUS_ONGOING,
    STATUS_FINISHED,
    DEFAULT_AUDIO_PATH,
    AZURE_SPEECH_REGION
)
from .languages import LANGUAGES
